// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.normandy.user_id", "1fdf53bc-1b70-4b8e-8fcc-cf30f9f898c5");
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1677089041);
user_pref("app.update.lastUpdateTime.region-update-timer", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{4a81a1b7-0f80-4a83-895e-2119bd6b64e0}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1677089035);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 128);
user_pref("browser.newtabpage.activity-stream.impressionId", "{35998a37-82bf-400d-9c26-1936106a54f7}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\"],\"idsInUrlbar\":[\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.policies.applied", true);
user_pref("browser.policies.runOncePerModification.displayBookmarksToolbar", "false");
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.region.update.updated", 1677089038);
user_pref("browser.search.region", "ID");
user_pref("browser.startup.couldRestoreSession.count", 1);
user_pref("browser.startup.homepage_override.buildID", "20221107191025");
user_pref("browser.startup.homepage_override.mstone", "102.5.0");
user_pref("browser.startup.lastColdStartupCheck", 1677089037);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\"],\"currentVersion\":17,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("distribution.Kali.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "102.5.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("doh-rollout.balrog-migration-done", true);
user_pref("doh-rollout.doneFirstRun", true);
user_pref("doh-rollout.home-region", "ID");
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("dom.push.userAgentID", "d879b182db7541a0af3ce24c158c278b");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20221107191025");
user_pref("extensions.lastAppVersion", "102.5.0");
user_pref("extensions.lastPlatformVersion", "102.5.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"doh-rollout@mozilla.org\":\"8a2f073b-8b44-46a0-8dbb-ea5173682839\",\"formautofill@mozilla.org\":\"1224b27a-8e83-48e2-b05d-aa9883610be3\",\"pictureinpicture@mozilla.org\":\"ae26811e-ec0b-431f-83fe-b8f0ae049343\",\"screenshots@mozilla.org\":\"e84efd60-0566-4b10-a044-7f57b768a1c9\",\"webcompat-reporter@mozilla.org\":\"7d416543-c3fb-4045-916b-ccc0062d40f9\",\"webcompat@mozilla.org\":\"c2db86b0-c05f-4d62-b083-cfd8739cec66\",\"default-theme@mozilla.org\":\"ed1960e7-3e7e-42f5-9089-c639ca1d46e7\",\"addons-search-detection@mozilla.com\":\"b2c087cf-7432-419d-a38b-76ed11d1093a\",\"google@search.mozilla.org\":\"5bacead1-e6a8-43f4-8504-4c025ca26083\",\"amazondotcom@search.mozilla.org\":\"f13e41e3-f0b5-43d6-a704-da2d833dc6c8\",\"wikipedia@search.mozilla.org\":\"254dbe3b-3e3f-4903-ac4e-18148f1402ba\",\"bing@search.mozilla.org\":\"2f5dce0d-d17e-4f3b-b0d9-064897d11599\",\"ddg@search.mozilla.org\":\"b78f9777-8bbf-4902-bdc7-e952068d4500\"}");
user_pref("fission.experiment.max-origins.last-disqualified", 0);
user_pref("fission.experiment.max-origins.last-qualified", 1677089039);
user_pref("fission.experiment.max-origins.qualified", true);
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "7ca568b8-768a-4299-8884-285b9505f40f");
user_pref("services.sync.engine.addresses.available", true);
user_pref("toolkit.startup.last_success", 1677089034);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20221107191025");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
